// <auto-generated />
using MemeThroneBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TheMemeThrone.Migrations
{
    [DbContext(typeof(MemingContext))]
    [Migration("20210405034238_CreateGame")]
    partial class CreateGame
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("MemeThroneBot.CaptionCard", b =>
                {
                    b.Property<int>("CaptionCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("CaptionCardId");

                    b.ToTable("CaptionCards");
                });

            modelBuilder.Entity("MemeThroneBot.GameState", b =>
                {
                    b.Property<int>("GameStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("GameStateId");

                    b.HasIndex("Guild")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MemeThroneBot.MemeCard", b =>
                {
                    b.Property<int>("MemeCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("MemeCardId");

                    b.ToTable("MemeCards");
                });
#pragma warning restore 612, 618
        }
    }
}
